let pecas = [
    { n: 'rei', a: 'R' },
    { n: 'Rainha', a: 'Q' },
    { n: 'Torre', a: 'R' },
    { n: 'Bispo', a: 'B' },
    { n: 'Cavalo', a: 'N' },
    { n: 'Peao', a: '' },
]

let opcoes = [
    { n: 'x', v: 'captura' },
    { n: '+', v: 'xeque' },
    { n: '++', v: 'xeque duplo' },
    { n: '#', v: 'mate' },
]

let jogs = [
    [
        'e4',
        'f4',
        'Nf3',
        'h4',
        'Ne5',
        'Nxg4',
        'd3',
        'Bxf4',
        'Qe2+',
        'Nf6+',
        'Bxc7+',
        'Nd5+',
        'Nxe7',
        'Qg4',
        'Qf4',
        'Qxf7',
        'Kd2',
        'Na3',
        'Qh5',
        'Qxh1',
        'Qh4+',
        'Rb1',
        'Qa4+'
    ],
    [
        'e5',
        'exf4',
        'g5',
        'g4',
        'Nf6',
        'Nxe4',
        'Ng3',
        'Nxh1',
        'Qe7',
        'Kd8',
        'Kxc7',
        'Kd8',
        'Bxe7',
        'd6',
        'Rg8',
        'Bxh4+',
        'Re8',
        'Na6',
        'Bf6',
        'Bxb2',
        'Kd7',
        'Bxa3 ',
    ]
]